export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const PROFILE_UPDATE_REQUEST = "PROFILE_UPDATE_REQUEST";
export const PROFILE_UPDATE_RESET = "PROFILE_UPDATE_RESET";
export const PROFILE_UPDATE_SUCCESS = "PROFILE_UPDATE_SUCCESS";
export const PROFILE_UPDATE_FAIL = "PROFILE_UPDATE_FAIL";

export const PASS_UPDATE_REQUEST = "PASS_UPDATE_REQUEST";
export const PASS_UPDATE_RESET = "PASS_UPDATE_RESET";
export const PASS_UPDATE_SUCCESS = "PASS_UPDATE_SUCCESS";
export const PASS_UPDATE_FAIL = "PASS_UPDATE_FAIL";

export const FORGET_PASS_REQUEST = "FORGET_PASS_REQUEST";
export const FORGET_PASS_SUCCESS = "FORGET_PASS_SUCCESS";
export const FORGET_PASS_FAIL = "FORGET_PASS_FAIL";

export const RESET_PASS_REQUEST = "RESET_PASS_REQUEST";
export const RESET_PASS_SUCCESS = "RESET_PASS_SUCCESS";
export const RESET_PASS_FAIL = "RESET_PASS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";